### PR TITLE
Router: format lambda in 1-arg call as with braces

### LINKED ISSUE #667: Move lambda arg to first line
This template is a guideline, not a strict requirement.
- **Version**: 0.5
- **Configuration**:
```
style = default
```

## Unexpected formatting output

Obtained, scalafmt formats code like this:
```scala
    val search: BinarySearch = new BinarySearch(
      guess =>
        this.calculateNumbers(
          state.copy(amount = guess, inputType = InputType.Income)))
```

Expected, I would like the formatted output to look like this:
```scala
    val search: BinarySearch = new BinarySearch(guess =>
      this.calculateNumbers(
        state.copy(amount = guess, inputType = InputType.Income)))
```

### PR DESCRIPTION
**Pull request by kitbellew**
N.B. fork of `scala-repos` showing the difference: https://github.com/kitbellew/scala-repos/commits/scalafmt-1551

Fixes #667

It is desirable to have an option to format paren lambda in calls just
like a curly-brace lambda. For instance, currently:

```
  call { parameter =>
    long_body
  }
```

but

```
  call(
    parameter =>
      long_body
  )
```

instead of the similar (and more compact)

```
  call(parameter =>
    long_body
  )
```

Obviously, when the call refers to multiple arguments (which is never
the case with curly-brace lambda), this formatting wouldn't make sense
and would continue to be

```
  call(
    parameter =>
      long_body,
    another_argument
  )
```

N.B. Using the existing `alwaysBeforeCurlyBraceLambdaParams` configuration parameter is also possible but it magically fixed an error with `align/ArrayIndexOutOfBounds800.source` test (even if I explicitly flipped the `alwaysBeforeCurlyBraceLambdaParams` setting) which, I think, is intended to fail.

### CODE REVIEW

**Comment by kitbellew** [comment]
@olafurpg @tanishiking @poslegm this is the other proposal I mentioned in #1549 , please take a look. I *think* it works as I intended.

**Comment by poslegm** [comment]
Thank you for it!

I will read the code later. Anyway it is a fix for https://github.com/scalameta/scalafmt/issues/667 (old and annoying issue) 👍 

Configuration flag is unnecessary because the issue marked as `should`. 
It should be just enhancement for scalafmt behavior, but with `edition` support (read more about editions and how to add it into your PR: https://github.com/scalameta/scalafmt/pull/1431).

**TODO** document editions on https://scalameta.org/scalafmt/docs/contributing-scalafmt.html

But we need to test changes very thoroughly. May be https://github.com/olafurpg/scala-repos would be helpful for regression testing.

**Comment by kitbellew** [comment]
@poslegm кто ж знал, что не только нас это беспокоило... посмотрю на editions.

п.с. а что насчет #1549?

**Comment by kitbellew** [comment]
@poslegm @tanishiking fyi: implemented editions but now working on that `scala-repos` test. on it, the changes are subtle but I am trying to minimize them. Will update when done.

File: scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala [hunk 1]
```diff
@@ -461,6 +462,39 @@ class Router(formatOps: FormatOps) {
...
+        val close = matchingParentheses(hash(formatToken.left))
+        val splitOnClosePolicy =
+          if (style.danglingParentheses.callSite && !lambdaIsABlock)
+            newlineOnTokenPolicy(close)
+          else
+            Policy(Policy.emptyPf, close.end)
+        val noSplitBeforeArrowPolicy =
+          splitOnClosePolicy.andThen(SingleLineBlock(lambdaToken))
+
+        val newlinePenalty = 3 + nestedApplies(leftOwner)
```
Comment (kitbellew) [inline scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala]: This part is voodoo. I started with `1` but ended up with this after testing on `scala-repos`.

File: scalafmt-tests/src/test/resources/newlines/beforeConfigSingleArgParenLambdaParamsF_danglingF.stat [hunk 2]
```diff
@@ -216,9 +193,9 @@ def f = {
 >>>
 EventFilter[ActorInitializationException](occurrences = 1) intercept {
   intercept[akka.actor.ActorInitializationException] {
-    wrap(
-      result ⇒
-        actorOf(Props(new OuterActor(
+    wrap(result ⇒
+      actorOf(
```
Comment (kitbellew) [inline scalafmt-tests/src/test/resources/newlines/beforeConfigSingleArgParenLambdaParamsF_danglingF.stat]: This split is the only thing I couldn't fix, played with penalties in that match branch where I added the "preserve no-split in assign" logic.

Specifically, the sum `nestedPenalty + lhsPenalty` seemed to be constant for each of these nested calls which doesn't indicate a preference between them.

I tried `2 * nestedPenalty + lhsPenalty` to try and split earlier but it ultimately produced too many changes. I also tried `nestedPenalty + 2 * lhsPenalty` to prefer a later split, but it was also not working as well. So I gave up.

File: scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala [hunk 3]
```diff
@@ -113,6 +113,9 @@ case class Newlines(
     avoidAfterYield: Boolean = true
 ) {
   val reader: ConfDecoder[Newlines] = generic.deriveDecoder(this).noTypos
+
+  def beforeSingleArgParenLambdaParams(implicit edition: Edition): Boolean =
```
Comment (olafurpg) [inline scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala]: Let's make this a val in `ScalafmtConfig` and remove the implicit edition variable.

File: scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala [hunk 4]
```diff
@@ -1535,3 +1581,19 @@ class Router(formatOps: FormatOps) {
       Seq(Split(Space, 0), Split(Newline, 1))
     }
 }
+
+private object Router {
+
+  def getAssignAtSingleArgCallSite(tree: Tree): Option[Term.Assign] =
```
Comment (olafurpg) [inline scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala]: Let's move these to `TreeOps`. The `Router.scala` file is already too big :)

File: scalafmt-tests/src/test/resources/default/SearchState.stat [hunk 5]
```diff
@@ -455,8 +455,8 @@ EventsResponse.fromJson(json, run).success.value.events should be(
     ))
 <<< react #458
   val TodoApp = ReactComponentB[Unit]("TodoApp")
-    .initialState(State(Nil, ""))
-    .renderS(($, s) =>
+    .initialState(State(Nil, "")).renderS(
```
Comment (olafurpg) [inline scalafmt-tests/src/test/resources/default/SearchState.stat]: Is this an desirable change? This case looks like a regression compared to before.

File: scalafmt-tests/src/test/resources/default/SearchState.stat [hunk 6]
```diff
@@ -469,16 +469,16 @@ EventsResponse.fromJson(json, run).success.value.events should be(
...
-      ($, s) =>
-        <.div(<.h3("TODO"),
-              TodoList(s.items),
-              <.form(
-                  ^.onSubmit ==> $._runState(handleSubmit), // runState runs a state monad and applies the result.
-                  <.input( // _runState is similar but takes a function-to-a-state-monad.
-                      ^.onChange ==> $._runState(acceptChange), // In these cases, the function will be fed the JS event.
-                      ^.value := s.text),
-                  <.button("Add #", s.items.length + 1))))
+  .renderS(($, s) =>
```
Comment (olafurpg) [inline scalafmt-tests/src/test/resources/default/SearchState.stat]: nice 👍

File: scalafmt-tests/src/test/resources/newdefault/SearchState.stat [hunk 7]
```diff
@@ -1,6 +1,7 @@
 style = default
 <<< forAll
-forAll(table)((reqProto, headReq, reqCH, resProto, resCH, resCD, renCH, close) ⇒
+forAll(table)(
+  (reqProto, headReq, reqCH, resProto, resCH, resCD, renCH, close) ⇒
```
Comment (olafurpg) [inline scalafmt-tests/src/test/resources/newdefault/SearchState.stat]: Is this also a desirable change?

File: scalafmt-tests/src/test/resources/newlines/beforeConfigSingleArgParenLambdaParamsF_danglingF.stat [hunk 8]
```diff
@@ -0,0 +1,270 @@
...
+  something.call (
+     (x, y) => {
+       g(x)
+       g(y)
+     }
+  )
+}
+>>>
+def f = {
+  something.call((x, y) => {
```
Comment (olafurpg) [inline scalafmt-tests/src/test/resources/newlines/beforeConfigSingleArgParenLambdaParamsF_danglingF.stat]: Nice!

File: scalafmt-tests/src/test/resources/newlines/beforeConfigSingleArgParenLambdaParamsF_danglingT.stat [hunk 9]
```diff
@@ -0,0 +1,289 @@
...
+            actorOf(Props(promiseIntercept(new FailingInnerActor)(result)))
+          )
+        )
+      )
+    }
+  }
+
+  contextStackMustBeEmpty()
+}
+<<< 16: prefer split on equals vs split on arrow in includedTerms
```
Comment (olafurpg) [inline scalafmt-tests/src/test/resources/newlines/beforeConfigSingleArgParenLambdaParamsF_danglingT.stat]: What is this case testing? I'm unable to spot the relevant line

File: scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala (hunk 1 above)
Comment (olafurpg) [reply scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala]: Mostly everything in the router is vodoo 😅 it's normal to reach some magic penalty based on running the formatter on scala-repos 👍

File: scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala (hunk 3 above)
Comment (kitbellew) [reply scalafmt-core/shared/src/main/scala/org/scalafmt/config/Newlines.scala]: will do

**Comment by kitbellew** [comment]
@olafurpg @tanishiking @poslegm here's a fork of `scala-repos` showing the difference:

https://github.com/kitbellew/scala-repos/commits/scalafmt-1551

File: scalafmt-tests/src/test/resources/default/SearchState.stat (hunk 5 above)
Comment (olafurpg) [reply scalafmt-tests/src/test/resources/default/SearchState.stat]: Whoops, for some reason I didn't see that. Looks great!

File: scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala [hunk 10]
```diff
@@ -192,6 +192,12 @@ case class ScalafmtConfig(
     continuationIndent.callSite,
     continuationIndent.defnSite
   )
+
+  def activeFor(edition: Edition): Boolean =
+    Edition.ordering.gteq(this.edition, edition)
+
+  def newlinesBeforeSingleArgParenLambdaParams: Boolean =
```
[the remark this answers is not in the document]
Comment (poslegm) [reply scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala]: Nitpicking: it should be a `val` because it's a constant value

[the remark this answers is not in the document]
Comment (kitbellew) [reply scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala]: will do in a minute

**Comment by kitbellew** [comment]
@poslegm amended to use `val`, agree it's better. also rebased on top of merged 1549.
