### PR TITLE
Router: for scala3, move NL before macro to after

### LINKED ISSUE #3188: Scalafmt 3.5.2 with scala3 dialect formats code that is not valid Scala 3
Related to https://github.com/scalameta/scalameta/issues/2727

We can see the issue happening here: https://github.com/scalameta/munit/pull/518

(I'm really sorry if my previous issue, linked above, didn't have enough details and inevitably caused us to end up here. :grimacing: ) 

## Configuration (required) ##
```
version = "3.5.2"
runner.dialect = scala3
```

## Command-line parameters (required) ##

When I run scalafmt via CLI like this: `scalafmt -c .scalafmt.conf test.scala`

## Steps

Given code like this:
```scala
package munit.internal

import munit.Clue
import scala.quoted._
import scala.language.experimental.macros

object MacroCompat {

  trait ClueMacro {
    inline implicit def generate[T](value: T): Clue[T] = ${ clueImpl('value) }
    implicit def generate[T](value: T): Clue[T] = macro MacroCompatScala2.clueImpl
  }

}
```

## Problem

Scalafmt formats code like this:
```scala
package munit.internal

import munit.Clue
import scala.quoted._
import scala.language.experimental.macros

object MacroCompat {

  trait ClueMacro {
    inline implicit def generate[T](value: T): Clue[T] = ${ clueImpl('value) }
    implicit def generate[T](value: T): Clue[T] =
      macro MacroCompatScala2.clueImpl
  }

}
```
Note the `macro MacroCompatScala2.clueImpl` on a new line.

Once formatted, scala 3.1.2 will not parse this code, yielding:
```
[error] -- [E103] Syntax Error: /home/andrew/src/scalafmttest/test.scala:12:6 ----------
[error] 12 |      macro MacroCompatScala2.clueImpl
[error]    |      ^^^^^
[error]    |      Illegal start of statement
```

## Expectation

The output format should be able to parsed by Scala 3

### PR DESCRIPTION
**Pull request by kitbellew**
Fixes #3188.

### CODE REVIEW

File: scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala [hunk 1]
```diff
@@ -2599,6 +2599,13 @@ class Router(formatOps: FormatOps) {
       case ft @ FormatToken(_: T.Comment, _, _) if ft.hasBreak =>
         splitsAsNewlines(splits)
       case ft if ft.meta.formatOff && ft.hasBreak => splitsAsNewlines(splits)
+      case FormatToken(_: T.Equals, r: T.KwMacro, _)
+          if dialect.allowInlineMods =>
```
Comment (kitbellew) [inline scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala:2603]: @tgodzik not sure if this is the right way to identify scala 3, perhaps as good as any

Comment (tgodzik) [reply scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala:2603]: I would use `allowSignificantIndentation`, because it's the cause of the issue. Without significant indentation there would be no issues

**Review by tgodzik — APPROVED** [review]
Just a small comment, otherwise LGTM

**Comment by kitbellew** [comment]
> Just a small comment, otherwise LGTM

Done.
