### PR TITLE
Scalafmt bugfix: restore .format signatures while passing filename

### LINKED ISSUE #1628: 2.3.3-RC1 always crashes with "classpath is corrupted"
I tried upgrading to 2.3.3-RC1 and I always get

 ```[error] scalafmt version 2.3.3-RC1 classpath is corrupted```

I've tried running `sbt clean update` and that did not help. This issue is not present with 2.3.2 so I do not believe it is my setup.

Thanks for the great tool, looking forward to using 2.3.3!

My configuration is:

```
version = "2.3.3-RC1"
maxColumn = 120 
rewrite.rules = [PreferCurlyFors, SortModifiers, AvoidInfix, SortImports]
trailingCommas = always
assumeStandardLibraryStripMargin = true
optIn.breakChainOnFirstMethodDot = false
spaces.inImportCurlyBraces = true
includeCurlyBraceInSelectChains = true
spaces.beforeContextBoundColon = Always
// These are copied from  https://scalameta.org/scalafmt/docs/configuration.html#other
rewrite.neverInfix.excludeFilters = [
  until
  to
  by
  eq
  ne
  "should.*"
  "contain.*"
  "must.*"
  in
  ignore
  be
  taggedAs
  thrownBy
  synchronized
  have
  when
  size
  only
  noneOf
  oneElementOf
  noElementsOf
  atLeastOneElementOf
  atMostOneElementOf
  allElementsOf
  inOrderElementsOf
  theSameElementsAs
  // these are new
  throws
  returns
  satisfy
]
```

### PR DESCRIPTION
**Pull request by kitbellew**
Create a new, package-private method `.formatCode` with the implementation based on the existing .format.

Make sure not to modify the existing interfaces of `.format` overloads, as they are externally expected (via reflection).

The bug was introduced in #1608 and removed the 3-parameter version of the `.format` overload as "unnecessary".

Fixes #1628.

### CODE REVIEW

**Comment by kitbellew** [comment]
@olafurpg @tanishiking @poslegm PTAL.

**Comment by tanishiking** [comment]
Thank you for the quick fix! I'll take a look this evening (UTC+09:00).

File: scalafmt-core/shared/src/main/scala/org/scalafmt/Scalafmt.scala [hunk 1]
```diff
@@ -82,6 +92,15 @@ object Scalafmt {
     }
   }
 
+  // XXX: don't modify signature, scalafmt-dynamic expects it via reflection
+  def format(
```
Comment (olafurpg) [inline scalafmt-core/shared/src/main/scala/org/scalafmt/Scalafmt.scala]: This looks like a new signature, did it exist in an older version of Scalafmt? Can you elaborate on how this fixes #1628

Comment (kitbellew) [reply scalafmt-core/shared/src/main/scala/org/scalafmt/Scalafmt.scala]: @olafurpg per our standard "i screwed up" practice, i reverted the original commit that breaks the contract (that's commit 1) and then added a second one which mainly restores the functionality but without touching the signatures of the two .format methods, you can probably see it by reviewing via the commits tab rather than the changes tab.

@tanishiking posted a stack trace yesterday which shows the failure to be in trying to find .format with the three-parameter signature, via reflection: https://github.com/scalameta/scalafmt/issues/1628#issuecomment-579372180

While I, unfortunately, don't have a way to reproduce the problem, this is most likely the only reason for #1628.

Comment (tanishiking) [reply scalafmt-core/shared/src/main/scala/org/scalafmt/Scalafmt.scala]: This regression had been introduced in https://github.com/scalameta/scalafmt/pull/1608 (sorry I missed this change), and this PR basically revert the root cause of this regression.

Basically, it's probably better to write a detailed description, so that even people (who don't follow the context) can understand the change :)

Comment (olafurpg) [reply scalafmt-core/shared/src/main/scala/org/scalafmt/Scalafmt.scala]: Thanks for the explanation! I haven't followed all the recent changes closely. It's very important that the `Scalafmt.scala` file does not have binary breaking changes. The `scalafmt-dynamic` interface is an attempt to provide a richer public API that is binary stable, but build tools already interface with the `Scalafmt` object so we need to keep supporting it
