### PR TITLE
Router: modify indent of case clauses consistently

### LINKED ISSUE #1244: Wrong indentation of closing paren if there are newlines and parentheses between "case" and "=>"
This template is a guideline, not a strict requirement.
- **Version**: 1.6.0-RC4
- **Integration**: sbt
- **Configuration**:
```
# default
```

## Steps

Given code like this:
```scala
x match {
  case Foo(
      a,
      b
  ) =>
    ???
}
```

When I run scalafmt like this:

```bash
$ sbt scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
x match {
  case Foo(
      a,
      b
      ) =>
    ???
}
```

## Expectation

I would like the formatted output to look like this:
```scala
x match {
  case Foo(
      a,
      b
  ) =>
    ???
}
```

## Workaround

There are no workarounds as far as I know.

### PR DESCRIPTION
**Pull request by kitbellew**
Fixes #1244. `scala-repos` diffs: https://github.com/kitbellew/scala-repos/commit/2877c2cc11ac8f6678023498766614669dfefa44

The existing logic was suppressing case pattern indentation which led to incorrect formatting relative to the end of the pattern.

Specifically, here's a problematic pattern:
```
    case pattern(
        argument // indent 1: explicitly suppressed
        ) // closing: clause indentation
          infix another( // indent 2: increased to distinguish from "if"
            ...
          ) if somethingLong
          .methodCalledBySomethingLong =>
      body
```

First, we need to restore indent 1. Second, we need to address indent 2 and there are several options:

* we choose NOT to keep it different from `if`, as `if` can be easily determined as the last line at that level of indentation; that way, we don't add extra indentation for infix, closing parens etc., so it looks like this:
```
    case pattern(
          argument // indent 1: added
        )
        infix another( // indent 2: removed
          ...
        ) if somethingLong
          .methodCalledBySomethingLong =>
      body
```
* if we wanted to keep it different from the `if` guard, we would then have to increase indentation of closing paren, to align with indent 2, which in turn means increasing indent 1, which leads to a bit too much indentation; also, since `if` is frequently tucked after the closing paren on the previous line but could be split, it might lead to an odd formatting like this (and doesn't really emphasize `if` anyway, unless we require a line break before `if`):
```
    case pattern(
            argument // indent 1: added twice
          ) // extra indent
          infix another( // indent 2: unchanged
            ...
          ) if somethingLong
          .methodCalledBySomethingLong =>
      body
```
* finally, an option that was being discussed in the ticket looks a bit like this:
```
    case pattern(
      argument
    )
    infix another(
      ...
    ) if somethingLong
          .methodCalledBySomethingLong =>
      body
```
which is still quite hard to read, as it doesn't really emphasize the `case` keyword, which is an even harder problem when there's no body and another case clause right after:
```
    case pattern1(
      argument
    )
    infix another(
      ...
    ) if guard =>
    case pattern2(
      argument
    )
    infix another(
      ...
    ) if guard =>
```

### CODE REVIEW

**Comment by kitbellew** [comment]
@olafurpg @poslegm PTAL

@tanishiking this addresses the issue you reported.

File: scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala [hunk 1]
```diff
@@ -609,4 +609,11 @@ object TreeOps {
       }
     }
 
+  def isChildOfCaseClause(tree: Tree): Boolean =
+    findTreeWithParent(tree) {
+      case t: Case => Some(tree ne t.body)
```
Comment (poslegm) [inline scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala]: What is reason to not use just `==`?

**Comment by poslegm** [comment]
P.S. there is a lot formatting changes already. May be cut 2.5.0-RC1 after this PR merging?

File: scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala (hunk 1 above)
Comment (kitbellew) [reply scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala]: i don't really know how `==` is implemented for trees but i'd like to check that it's *the same exact* instance here rather than something which looks the same.

**Comment by kitbellew** [comment]
> P.S. there is a lot formatting changes already. May be cut 2.5.0-RC1 after this PR merging?

can we get through the `fold/unfold` changes i have so far before we do so? i have 12 additional changes already prepared, have just been submitting them one at a time, to make reviewing easier. would you prefer it if i sent them all at once, in one PR?

**Comment by poslegm** [comment]
Yes, of course. Submit it as you prefer :)

(But as I know scala-stewars don't sell PRs with RC releases. So we can cut it often enough)
