### PR TITLE
FormatWriter: optionally support multiline align

### LINKED ISSUE #1504: Case arrows not aligning
I've a question regarding alignment on cases for a match expression. It looks like
the arrows are not lining up with `aligh = some` or `align = more`
- **Version**: 2.0.0
- **Integration**: IntelliJ
- **Configuration**:
```
maxColumn = 100
docstrings = ScalaDoc // default
continuationIndent.callSite = 2
continuationIndent.defnSite = 2
continuationIndent.extendSite = 2

// Alignment settings
align = some
align.arrowEnumeratorGenerator = false
align.openParenCallSite = false
align.openParenDefnSite = false // default but setting for reminder

newlines.alwaysBeforeTopLevelStatements = true
newlines.afterCurlyLambda = never

binPack.parentConstructors = true
importSelectors = binPack

verticalMultiline.atDefnSite = false

includeCurlyBraceInSelectChains = true
includeNoParensInSelectChains = false // this is the default value
indentYieldKeyword = true

optIn.breakChainOnFirstMethodDot = false
optIn.blankLineBeforeDocstring = true

trailingCommas = never
lineEndings = unix

rewrite.rules = [SortImports, RedundantBraces, RedundantParens, SortModifiers, PreferCurlyFors]

danglingParentheses = true
```

## Steps

Given code like this:
```scala
  trait Identifier

  case class SuperFooBarIdentifier(identifyingid: String) extends Identifier

  case class TastyBarIdentifier (ider: String, int: Int) extends Identifier

  case class BazBar(identifier: Identifier)

  val stringFoo = thing.identifier match {
    case foo : SuperFooBarIdentifier => "somestring" / "other_string" / foo.identifyingid
    case tastyBar: TastyBarIdentifier => "something" / "other_other" ? ("arg1" -> tastyBar.ider) & ("limit" -> 111)
    case unknown => throw new IllegalArgumentException(s"Not sure at all what kinda class this is: ${unknown.getClass}")
  }
```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
val stringFoo = thing.identifier match {
    case foo: SuperFooBarIdentifier => "somestring" / "other_string" / foo.identifyingid
    case tastyBar: TastyBarIdentifier =>
      "something" / "other_other" ? ("arg1" -> tastyBar.ider) & ("limit" -> 111)
    case unknown =>
      throw new IllegalArgumentException(
        s"Not sure at all what kinda class this is: ${unknown.getClass}"
      )
  }
```

## Expectation

I would like the formatted output to look like this:
```scala
  val stringFoo = thing.identifier match {
    case foo: SuperFooBarIdentifier   => "somestring" / "other_string" / foo.identifyingid
    case tastyBar: TastyBarIdentifier =>
      "something" / "other_other" ? ("arg1" -> tastyBar.ider) & ("limit" -> 111)
    case unknown                      =>
      throw new IllegalArgumentException(
        s"Not sure at all what kinda class this is: ${unknown.getClass}"
      )
  }
```

### LINKED ISSUE #1811: Preserve alignment in for comprehension with multiline
- **Configuration**:
```
version = 2.4.2
align = most
```

## Steps

Given code like this:
```scala
for {
  a   <- Option(1)
  bbb <- Option(2)
  cccccc <- Option {
    3
   }
} yield ()
```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
for {
  a   <- Option(1)
  bbb <- Option(2)
  cccccc <- Option {
             3
           }
} yield ()
```

## Expectation

I would like the formatted output to look like this:
```scala
for {
  a      <- Option(1)
  bbb    <- Option(2)
  cccccc <- Option {
              3
            }
} yield ()
```

### LINKED ISSUE #1841: Fails to align with equals if line is wrapped
## Relevant config
```
version = 2.4.2
style = defaultWithAlign
```

## Steps

Upgrading from `2.3.2` to `2.4.2` gives the following. The wrap is correct as it is greater than the default but wrapping makes the equals not align anymore:
```scala
-  private final val countGPRegisters  = 6
-  private final val countFPRegisters  = 8
-  private final val fpRegisterWords   = 2
-  private final val registerSaveWords = countGPRegisters + countFPRegisters * fpRegisterWords
+  private final val countGPRegisters = 6
+  private final val countFPRegisters = 8
+  private final val fpRegisterWords  = 2
+  private final val registerSaveWords =
+    countGPRegisters + countFPRegisters * fpRegisterWords
```
Also this.
```scala
-  private[this] val pbClass       = Class.forName("java.lang.ProcessBuilder")
-  private[this] val redirectClass = pbClass.getClasses find (_.getSimpleName == "Redirect")
+  private[this] val pbClass = Class.forName("java.lang.ProcessBuilder")
+  private[this] val redirectClass =
+    pbClass.getClasses find (_.getSimpleName == "Redirect")
```

### PR DESCRIPTION
**Pull request by kitbellew**
To support this, also fix a couple of issues:

* include align gap in width:
  * because we sort on the width, we might end up with (width+gap) for the currently widest alignment spot to be less than for another, with a smaller width.
* stop align container search
  * there's a different class of containers (currently, "case"), which would only serve as a container for tokens which are formatted below it, and for tokens on the same line, we would continue the search, so that those tokens would align together with the case arrow.

Fixes #1504.
Fixes #1811.
Fixes #1841.

### CODE REVIEW

File: scalafmt-core/shared/src/main/scala/org/scalafmt/config/Align.scala [hunk 1]
```diff
@@ -61,6 +61,7 @@ import metaconfig.generic.Surface
   *   of the first line, as usual.
   */
 case class Align(
+    multiline: Boolean = false,
```
Comment (poslegm) [inline scalafmt-core/shared/src/main/scala/org/scalafmt/config/Align.scala:64]: Test cases looks great. Does this have to be a separate option? May be just apply it for `align!=none`?

File: scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala [hunk 2]
```diff
@@ -376,6 +373,155 @@ class FormatWriter(formatOps: FormatOps) {
...
+      else {
+        var columnShift = 0
+        val finalResult = Map.newBuilder[TokenHash, Int]
+
+        // all blocks must be here, to get final flush
+        val blocks = new mutable.HashMap[Tree, AlignBlock]
+        def createBlock(x: Tree) = blocks.getOrElseUpdate(x, new AlignBlock)
+        var prevAlignContainer: Tree = null
+        var prevBlock: AlignBlock =
+          if (initStyle.align.multiline) null else createBlock(null)
```
Comment (poslegm) [inline scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala:397]: What is purpose of `createBlock(null)` here? Is it necessary to have map with single empty block on line 456?

File: scalafmt-core/shared/src/main/scala/org/scalafmt/config/Align.scala (hunk 1 above)
Comment (kitbellew) [reply scalafmt-core/shared/src/main/scala/org/scalafmt/config/Align.scala:64]: if we enable this code by default, everyone's code will change and people will complain. this is a potentially massive change.

File: scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala [hunk 3]
```diff
@@ -376,6 +373,155 @@ class FormatWriter(formatOps: FormatOps) {
...
+            if (doubleNewline || matches == 0 && shouldFlush(alignContainer))
+              flushNonEmptyAlignBlock(block, finalResult)
+          }
+          if (alignContainer ne null) {
+            prevAlignContainer = alignContainer
+            prevBlock = block
+            if (block.isEmpty && !doubleNewline) block += candidates
+          }
+        }
+        blocks.valuesIterator.foreach { x =>
```
Comment (kitbellew) [inline scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala:456]: this is the flush i am referring to above, on `createBlock`.

File: scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala [hunk 4]
```diff
@@ -376,6 +373,155 @@ class FormatWriter(formatOps: FormatOps) {
...
+            if (matches > 0) {
+              // truncate candidates if matches are shorter than both lists
+              val truncate =
+                matches < prev.length && matches < candidates.length
+              if (truncate) {
+                block(block.length - 1) = prev.take(matches)
+                block += candidates.take(matches)
+              } else block += candidates
+            }
+            if (doubleNewline || matches == 0 && shouldFlush(alignContainer))
```
Comment (kitbellew) [inline scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala:447]: this line would need another check for non-multiline case (see comments on `createBlock`).

File: scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala (hunk 2 above)
Comment (kitbellew) [reply scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala:397]: i considered that adding a map with a single entry for an entire document is very cheap. otherwise, see two comments below, that code would have to be modified to distinguish between multiline and non-multiline, which increases clutter.

but if you prefer, i can easily change that.

File: scalafmt-core/shared/src/main/scala/org/scalafmt/config/Align.scala (hunk 1 above)
Comment (poslegm) [reply scalafmt-core/shared/src/main/scala/org/scalafmt/config/Align.scala:64]: Yes, it's a valid point. But what about true by default?

File: scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala (hunk 2 above)
Comment (poslegm) [reply scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala:397]: No, it's just clarification 👍

File: scalafmt-core/shared/src/main/scala/org/scalafmt/config/Align.scala (hunk 1 above)
Comment (kitbellew) [reply scalafmt-core/shared/src/main/scala/org/scalafmt/config/Align.scala:64]: i'd leave it to you and @olafurpg to decide if you want to change defaults :)

i think it would be ok to include it as default in `align.preset = most` as it is advertised in the configuration as likely to be aggressive and also change in the future.

Comment (poslegm) [reply scalafmt-core/shared/src/main/scala/org/scalafmt/config/Align.scala:64]: True for `most` preset is optimal solution

Comment (kitbellew) [reply scalafmt-core/shared/src/main/scala/org/scalafmt/config/Align.scala:64]: done. also added documentation.

Comment (olafurpg) [reply scalafmt-core/shared/src/main/scala/org/scalafmt/config/Align.scala:64]: True for most sounds good.
