### PR TITLE
Router: always skip shebang line

### LINKED ISSUE #3267: Support shebang in .scala files with the Scala 3 dialect
## Configuration (required) ##
```
version = 3.5.8
runner.dialect = scala3
```

## Steps

Given code like this:
```scala
#!/usr/bin/env scala

@main def run() = println("hello world!")
```

## Problem

Scalafmt formats code like this:
```
.../main.scala:1: error: [dialect scala3] illegal start of definition identifier
#!/usr/bin/env scala
^
```

## Expectation

The file is legal scala3 (can be run with `scala main.scala` and compiled with `scalac main.scala`), and should be formatted while ignoring the first line.

## Notes

There seems to be supported for ammonite scripts, or rather anything with a `.sc` file ending

### PR DESCRIPTION
**Pull request by kitbellew**
Fixes #3267.

### CODE REVIEW

File: scalafmt-core/shared/src/main/scala/org/scalafmt/Scalafmt.scala [hunk 1]
```diff
@@ -67,7 +67,7 @@ object Scalafmt {
   ): Formatted.Result = {
     def getStyleByFile(style: ScalafmtConfig) = {
       val isSbt = FileOps.isAmmonite(filename) || FileOps.isSbt(filename) ||
-        FileOps.isMarkdown(filename)
+        FileOps.isMarkdown(filename) || code.startsWith("#!")
```
Comment (tgodzik) [inline scalafmt-core/shared/src/main/scala/org/scalafmt/Scalafmt.scala:70]: Is this the line that would allow toplevel statements like in sbt? Though Scala 3 only allows toplevel definitions and not statements, I don't think we need to change anything since it's included in the dialect.

Comment (kitbellew) [reply scalafmt-core/shared/src/main/scala/org/scalafmt/Scalafmt.scala:70]: yes, that's the line. it doesn't change the dialect to "sbt" but simply enables allowTopLevelStatements.

on a different note: perhaps the formatter should probably always allow top level since its job is not to validate code but to format it 😀

Comment (tgodzik) [reply scalafmt-core/shared/src/main/scala/org/scalafmt/Scalafmt.scala:70]: Maybe? That shouldn't influence the formatting at all. We can use a more inclusive dialect.

Comment (tgodzik) [reply scalafmt-core/shared/src/main/scala/org/scalafmt/Scalafmt.scala:70]: But anyway, I don't think we need to enable toplevel statements when shebang is present. I doesn't really change the Scala 3 behaviour. That's just 5 five cents 😅

Comment (kitbellew) [reply scalafmt-core/shared/src/main/scala/org/scalafmt/Scalafmt.scala:70]: ok, let me split these two up.

**Review by tgodzik — APPROVED** [review]
LGTM, thanks!
