### PR TITLE
FormatOps: don't format infix as patterns for val

### LINKED ISSUE #3313: afterInfix breaks long destructuring pattern causing compiler error
UPDATE:

Hi,
When formatting a simple destructuring statement using ~`maxColumn`~ `afterInfix=many` the compiler stops recognizing the pattern.
for example:
```
val servicePort :: producerServerPort :: grpcSidecarServicePort :: managementPort :: grpcSidecarUserPort :: jsonRpcSidecarUserPort :: Nil = selectRandomPorts(6)
```
becomes
```
val servicePort :: producerServerPort :: grpcSidecarServicePort :: managementPort :: grpcSidecarUserPort :: jsonRpcSidecarUserPort :: 
Nil = selectRandomPorts(6)
```

and will result in 
```
error: illegal start of simple pattern
Nil = selectRandomPorts(6)
```

scalafmt.conf:
```
version=3.5.9
runner.dialect=scala212

maxColumn = 140
newlines {
  afterInfix=many
}
```

Note: Compiling in Scala 2.12

### PR DESCRIPTION
**Pull request by kitbellew**
Fixes #3313.

### CODE REVIEW

File: scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala [hunk 1]
```diff
@@ -505,7 +505,18 @@ class FormatOps(
         val afterInfix = style.breakAfterInfix(t)
         if (afterInfix ne Newlines.AfterInfix.keep) {
           if (ft.meta.leftOwner ne app.op) Seq(Split(Space, 0))
-          else InfixSplits(app, ft).getBeforeLhsOrRhs(afterInfix)
+          else {
+            val fullInfixApp = InfixSplits.findEnclosingInfix(app)
+            val fullInfix = fullInfixApp.all
+            val ok = isEnclosedInParens(fullInfix) || fullInfix.parent.exists {
+              case t: Defn.Val => t.rhs eq fullInfix
```
Comment (tgodzik) [inline scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala:512]:
```suggestion
              case t: Defn.Val => t.pat eq fullInfix
```
shouldn't we check the pattern and not rhs?

**Review by tgodzik — CHANGES_REQUESTED** [review]
It seems the tests are failing :thinking:

**Review by tgodzik — APPROVED** [review]
LGTM then!
